title: ほのぼの日記/むくり/横転/萌え/エモ/物語/ノベル/遊泳/読書/創作/おひるね/おさんぽ
description: ほのぼの日記/むくり/横転/萌え/エモ/物語/ノベル/遊泳/読書/創作/おひるね/おさんぽ
url: "https://gydggufjdb.github.io"
baseurl: "/ofutongeo"
permalink: /:year/:month/:day/:title/
markdown: kramdown